spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

logging:
  file:
    name: logs/app.log
  level:
    root: info
    com:
      mprog: trace
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 10

