spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
#    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
#
#server:
#  error:
#    include-binding-errors: always
#    include-message: always

logging:
  file:
    name: logs/app.log
  level:
    root: info
    com:
      mprog: trace
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 10